### ISSUE TITLE
undefined method `dst?' for 0:Integer

### ISSUE THREAD

**Issue by guemidiborhane** [Shopify/maintenance_tasks#585]
Hello,

we're trying to migrate our rake tasks to maintenance_tasks gem which will greatly improve our data update flow, but we're hitting a hard wall for now (see the title).

we tried to do some investigation and we suspect it has something to do with the  [ `tasks_helper#time_running_in_words`](https://github.com/Shopify/maintenance_tasks/blob/89e3530a22898b98f33391a8e500054a9a0dd43e/app/helpers/maintenance_tasks/tasks_helper.rb#L73), of course this is not final.

Thanks in advance for any help.

**Comment by etiennebarrie** [comment]
Can you share a backtrace? Thanks

**Comment by guemidiborhane** [comment]
Hey,

Here's the backtrace:

```
dotiw (5.3.1) lib/dotiw/time_hash.rb:21:in `initialize'
dotiw (5.3.1) lib/dotiw/methods.rb:11:in `new'
dotiw (5.3.1) lib/dotiw/methods.rb:11:in `distance_of_time_in_words_hash'
dotiw (5.3.1) lib/dotiw/methods.rb:34:in `distance_of_time_in_words'
dotiw (5.3.1) lib/dotiw/action_view/helpers/date_helper.rb:14:in `distance_of_time_in_words'
maintenance_tasks (1.8.1) app/helpers/maintenance_tasks/tasks_helper.rb:73:in `time_running_in_words'
maintenance_tasks (1.8.1) app/views/maintenance_tasks/runs/info/_succeeded.html.erb:2
actionview (6.1.4.6) lib/action_view/base.rb:247:in `public_send'
actionview (6.1.4.6) lib/action_view/base.rb:247:in `_run'
actionview (6.1.4.6) lib/action_view/template.rb:154:in `block in render'
activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.4.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
sentry-rails (4.1.5) lib/sentry/rails/tracing.rb:41:in `instrument'
activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `instrument'
actionview (6.1.4.6) lib/action_view/template.rb:345:in `instrument_render_template'
actionview (6.1.4.6) lib/action_view/template.rb:152:in `render'
actionview (6.1.4.6) lib/action_view/renderer/partial_renderer.rb:285:in `block in render_partial_template'
activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.4.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
sentry-rails (4.1.5) lib/sentry/rails/tracing.rb:41:in `instrument'
activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `instrument'
actionview (6.1.4.6) lib/action_view/renderer/partial_renderer.rb:280:in `render_partial_template'
actionview (6.1.4.6) lib/action_view/renderer/partial_renderer.rb:271:in `render'
actionview (6.1.4.6) lib/action_view/renderer/renderer.rb:81:in `render_partial_to_object'
actionview (6.1.4.6) lib/action_view/renderer/renderer.rb:53:in `render_partial'
actionview (6.1.4.6) lib/action_view/helpers/rendering_helper.rb:45:in `render'
maintenance_tasks (1.8.1) app/views/maintenance_tasks/tasks/_task.html.erb:15
actionview (6.1.4.6) lib/action_view/base.rb:247:in `public_send'
actionview (6.1.4.6) lib/action_view/base.rb:247:in `_run'
actionview (6.1.4.6) lib/action_view/template.rb:154:in `block in render'
activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.4.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
sentry-rails (4.1.5) lib/sentry/rails/tracing.rb:41:in `instrument'
activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `instrument'
actionview (6.1.4.6) lib/action_view/template.rb:345:in `instrument_render_template'
actionview (6.1.4.6) lib/action_view/template.rb:152:in `render'
actionview (6.1.4.6) lib/action_view/renderer/collection_renderer.rb:189:in `block in collection_with_template'
actionview (6.1.4.6) lib/action_view/renderer/collection_renderer.rb:70:in `block in each_with_info'
actionview (6.1.4.6) lib/action_view/renderer/collection_renderer.rb:70:in `each'
actionview (6.1.4.6) lib/action_view/renderer/collection_renderer.rb:70:in `each_with_info'
actionview (6.1.4.6) lib/action_view/renderer/collection_renderer.rb:180:in `each'
actionview (6.1.4.6) lib/action_view/renderer/collection_renderer.rb:180:in `map'
actionview (6.1.4.6) lib/action_view/renderer/collection_renderer.rb:180:in `collection_with_template'
actionview (6.1.4.6) lib/action_view/renderer/collection_renderer.rb:162:in `block (2 levels) in render_collection'
actionview (6.1.4.6) lib/action_view/renderer/partial_renderer/collection_caching.rb:21:in `cache_collection_render'
actionview (6.1.4.6) lib/action_view/renderer/collection_renderer.rb:161:in `block in render_collection'
activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.4.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
sentry-rails (4.1.5) lib/sentry/rails/tracing.rb:41:in `instrument'
activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `instrument'
actionview (6.1.4.6) lib/action_view/renderer/collection_renderer.rb:147:in `render_collection'
actionview (6.1.4.6) lib/action_view/renderer/collection_renderer.rb:119:in `render_collection_with_partial'
actionview (6.1.4.6) lib/action_view/renderer/renderer.rb:72:in `render_partial_to_object'
actionview (6.1.4.6) lib/action_view/renderer/renderer.rb:27:in `render_to_object'
actionview (6.1.4.6) lib/action_view/renderer/renderer.rb:22:in `render'
actionview (6.1.4.6) lib/action_view/helpers/rendering_helper.rb:38:in `block in render'
actionview (6.1.4.6) lib/action_view/base.rb:273:in `in_rendering_context'
actionview (6.1.4.6) lib/action_view/helpers/rendering_helper.rb:34:in `render'
maintenance_tasks (1.8.1) app/views/maintenance_tasks/tasks/index.html.erb:20
actionview (6.1.4.6) lib/action_view/base.rb:247:in `public_send'
actionview (6.1.4.6) lib/action_view/base.rb:247:in `_run'
actionview (6.1.4.6) lib/action_view/template.rb:154:in `block in render'
activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.4.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
sentry-rails (4.1.5) lib/sentry/rails/tracing.rb:41:in `instrument'
activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `instrument'
actionview (6.1.4.6) lib/action_view/template.rb:345:in `instrument_render_template'
actionview (6.1.4.6) lib/action_view/template.rb:152:in `render'
actionview (6.1.4.6) lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.4.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
sentry-rails (4.1.5) lib/sentry/rails/tracing.rb:41:in `instrument'
activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `instrument'
actionview (6.1.4.6) lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
actionview (6.1.4.6) lib/action_view/renderer/template_renderer.rb:71:in `block in render_with_layout'
activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.4.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
sentry-rails (4.1.5) lib/sentry/rails/tracing.rb:41:in `instrument'
activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `instrument'
actionview (6.1.4.6) lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
actionview (6.1.4.6) lib/action_view/renderer/template_renderer.rb:55:in `render_template'
actionview (6.1.4.6) lib/action_view/renderer/template_renderer.rb:11:in `render'
actionview (6.1.4.6) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
actionview (6.1.4.6) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (6.1.4.6) lib/action_view/rendering.rb:117:in `block in _render_template'
actionview (6.1.4.6) lib/action_view/base.rb:273:in `in_rendering_context'
actionview (6.1.4.6) lib/action_view/rendering.rb:116:in `_render_template'
actionpack (6.1.4.6) lib/action_controller/metal/streaming.rb:218:in `_render_template'
actionview (6.1.4.6) lib/action_view/rendering.rb:103:in `render_to_body'
actionpack (6.1.4.6) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (6.1.4.6) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (6.1.4.6) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (6.1.4.6) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (6.1.4.6) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
/usr/local/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
activesupport (6.1.4.6) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (6.1.4.6) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
actionpack (6.1.4.6) lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
activerecord (6.1.4.6) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
actionpack (6.1.4.6) lib/action_controller/metal/instrumentation.rb:45:in `render'
wicked_pdf (2.1.0) lib/wicked_pdf/pdf_helper.rb:46:in `call'
wicked_pdf (2.1.0) lib/wicked_pdf/pdf_helper.rb:46:in `render_with_wicked_pdf'
wicked_pdf (2.1.0) lib/wicked_pdf/pdf_helper.rb:30:in `render'
actionpack (6.1.4.6) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
actionpack (6.1.4.6) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
actionpack (6.1.4.6) lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
actionpack (6.1.4.6) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.1.4.6) lib/abstract_controller/base.rb:228:in `process_action'
actionpack (6.1.4.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.1.4.6) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.1.4.6) lib/active_support/callbacks.rb:106:in `run_callbacks'
actionpack (6.1.4.6) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.1.4.6) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.1.4.6) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.4.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
sentry-rails (4.1.5) lib/sentry/rails/tracing.rb:41:in `instrument'
activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `instrument'
actionpack (6.1.4.6) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
actionpack (6.1.4.6) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
activerecord (6.1.4.6) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.1.4.6) lib/abstract_controller/base.rb:165:in `process'
actionview (6.1.4.6) lib/action_view/rendering.rb:39:in `process'
actionpack (6.1.4.6) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.1.4.6) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.1.4.6) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.1.4.6) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.1.4.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (6.1.4.6) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.1.4.6) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.1.4.6) lib/action_dispatch/routing/route_set.rb:842:in `call'
railties (6.1.4.6) lib/rails/engine.rb:539:in `call'
railties (6.1.4.6) lib/rails/railtie.rb:207:in `public_send'
railties (6.1.4.6) lib/rails/railtie.rb:207:in `method_missing'
actionpack (6.1.4.6) lib/action_dispatch/routing/mapper.rb:20:in `block in <class:Constraints>'
actionpack (6.1.4.6) lib/action_dispatch/routing/mapper.rb:49:in `serve'
actionpack (6.1.4.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (6.1.4.6) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.1.4.6) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.1.4.6) lib/action_dispatch/routing/route_set.rb:842:in `call'
turnout (2.5.0) lib/rack/turnout.rb:25:in `call'
sentry-rails (4.1.5) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'
meta_request (0.7.3) lib/meta_request/middlewares/app_request_handler.rb:15:in `call'
meta_request (0.7.3) lib/meta_request/middlewares/meta_request_handler.rb:15:in `call'
bullet (7.0.0) lib/bullet/rack.rb:15:in `call'
lib/rack/robots.rb:10:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.1.4.6) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
actionpack (6.1.4.6) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.1.4.6) lib/action_dispatch/middleware/cookies.rb:689:in `call'
activerecord (6.1.4.6) lib/active_record/migration.rb:601:in `call'
actionpack (6.1.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.6) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
rack-contrib (2.3.0) lib/rack/contrib/response_headers.rb:19:in `call'
meta_request (0.7.3) lib/meta_request/middlewares/headers.rb:18:in `call'
web-console (4.0.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.1) lib/web_console/middleware.rb:19:in `block in call'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `call'
actionpack (6.1.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.6) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.6) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.6) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.6) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.1.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (6.1.4.6) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.6) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.6) lib/action_dispatch/middleware/host_authorization.rb:113:in `call'
rack-mini-profiler (2.0.2) lib/mini_profiler/profiler.rb:312:in `call'
sentry-ruby (4.1.4) lib/sentry/rack/capture_exceptions.rb:29:in `block in call'
sentry-ruby (4.1.4) lib/sentry/hub.rb:52:in `with_scope'
sentry-ruby (4.1.4) lib/sentry-ruby.rb:147:in `with_scope'
sentry-ruby (4.1.4) lib/sentry/rack/capture_exceptions.rb:14:in `call'
webpacker (5.1.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.1.4.6) lib/rails/engine.rb:539:in `call'
rack (2.2.3) lib/rack/urlmap.rb:74:in `block in call'
rack (2.2.3) lib/rack/urlmap.rb:58:in `each'
rack (2.2.3) lib/rack/urlmap.rb:58:in `call'
puma (4.3.11) lib/puma/configuration.rb:228:in `call'
puma (4.3.11) lib/puma/server.rb:718:in `handle_request'
puma (4.3.11) lib/puma/server.rb:472:in `process_client'
puma (4.3.11) lib/puma/server.rb:328:in `block in run'
puma (4.3.11) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by nvasilevski** [comment]
So indeed it seems like the `dotiw` is the cause. However I believe in this case it would be suitable to change the `dotiw` gem to support the same way of calling  `ActionView::Helpers::DateHelper#distance_of_time_in_words` supports
https://api.rubyonrails.org/v7.0.1/classes/ActionView/Helpers/DateHelper.html#method-i-distance_of_time_in_words

**Comment by guemidiborhane** [comment]
@nvasilevski i submitted a PR, is the solution bad?

**Comment by nvasilevski** [comment]
It's not bad, I just think that it's a little unsuitable to apply it here while the issue is caused by a gem that is not a dependency of the `maintenance_tasks` gem.
Like what if there is a one more gem that is going to break because of using time objects instead of integers that we use right now? Would we need to revert the fix? It's not going to be sustainable to flip-flop the logic on every compatibility issue caused by some patched methods.
In other words, I just want to mention the following point of view:
"There is not much to fix as long as it's not reproducible on a vanilla Rails application with dependencies that are defined in the maintenance tasks `gemspec`"

I still believe that ideal solution would be for `dotiw` gem to properly support `distance_of_time_in_words` method by matching all possible use-cases if it patches it. And also I truly believe that the  `dotiw` can benefit from this improvement 

I'm not against the suggested fix as long as it works with the native Rails `distance_of_time_in_words` method, I just feel like that the point described above is worth to be mentioned.

**Comment by nvasilevski** [comment]
It looks like we agreed that the root cause lives in another library
